### ISSUE TITLE
Incognito mode + localhost ERROR Error: Uncaught (in promise): Error: Login required

### ISSUE THREAD

**Issue by JacekKruzel** [auth0/auth0-angular#106] opened 2021-01-08 12:00 UTC
### Describe the problem

For the bug to reprocude, following conditions must be met:

- app is served from **localhost** (dev mode)
- using chrome in incognito mode
- scenario leveraging auth0 interceptor that adds proper token to the request

Due to incognito mode auth0 does not send all the cookies, so instead of getting token silently it does the full flow. Afther that is sucessfully obtains an acess token. Saying that,  when above conditions are met, auth0 fails to add the token to the requests and tries to authorize again - this time with propmt param set to none (my gues is ib this moment the lib ties to obtain token silently).  In console _ERROR Error: Uncaught (in promise): Error: Login required_ error is visible, and requests  **are not** beeing sent.

![5](https://user-images.githubusercontent.com/77151040/104012402-08489300-51b0-11eb-9c9a-8200506c5564.png)

![2](https://user-images.githubusercontent.com/77151040/104012154-9ff9b180-51af-11eb-8a37-04db1c467f7f.png)

![3](https://user-images.githubusercontent.com/77151040/104012152-9ff9b180-51af-11eb-8bf0-fd3f99e57d16.png)

![4](https://user-images.githubusercontent.com/77151040/104012148-9ec88480-51af-11eb-8da6-fa616902a108.png)

### What was the expected behavior?

The second and following authorization endpoint calls should not happen. Requests should be sent with proper token attached.

### Reproduction

- use auth0 interceptor 
- serve app locally
- open chrome in incognito mode
- go to http://localhost:PORT
- call any endpoint that requires authentication

### Environment

- Angular 11
- @auth0/auth0-angular@1.3.1
- @auth0/auth0-spa-js@1.13.5

**Comment by frederikprijck** [comment] 2021-01-08 13:10
If you get the login_required error, you need to catch this error and ensure the user is authenticated by calling AuthService.loginWithRedirect. 

As I already mentioned on https://github.com/auth0/auth0.js/issues/1146#issuecomment-756717882, we have a PR open that is about the get merged that allows you to track this error and react accordingly as explained in the examples in that PR: auth0/auth0-angular#104

Also, the SDK is going to have issues when using incognito mode, see: https://github.com/auth0/auth0-spa-js/issues/682#issuecomment-756099316

**Comment by JacekKruzel** [comment] 2021-01-10 19:38
> If you get the login_required error, you need to catch this error and ensure the user is authenticated by calling AuthService.loginWithRedirect.

a) There is no way for me to catch this exception as it is not thrown by any of my code, but rather some async action (see the red callstack from first picture)

b) My understanding is, that when using interceptor, if im not signed in, i will be redirected to the sign-in page automatically. In fact this is exactly what happens. Only then, **after signing in and obteining token sucessfully** the error happens.

**Comment by frederikprijck** [comment] 2021-01-10 20:14
> a) There is no way for me to catch this exception as it is not thrown by any of my code, but rather some async action (see the red callstack from first picture)

The idea should be that you are able to catch this error using the `errors$` observable and react accordingly. However, you might need the changes of the above mentioned PR.

> b) My understanding is, that when using interceptor, if im not signed in, i will be redirected to the sign-in page automatically. In fact this is exactly what happens. Only then, after signing in and obteining token sucessfully the error happens.

This is not how the interceptor works. The interceptor does not do any redirect to the sign in page. The only thing that does that is the AuthGuard. The interceptor will try to silently get a token if needed, either using an iframe (which does not work in incognito) or using refresh tokens.

I tried reproducing this but the following works fine for me:

- Open Incognito Chrome
- Use a Route that is protected using the AuthGuard and navigate to it, I am redirected to the Signin Page
- Sign in and come back
- Execute an API call that uses the Interceptor
- The token is added to the API call and no error is logged in the console.

Can you try reproducing it using our sample at https://github.com/auth0-samples/auth0-angular-samples?

Steps to be taken to run this application is:

- Clone the repo
- `npm install` inside **Sample-01**
- rename `auth_config.json.example` to `auth_config.json` and fill in the parameters inside `Sample-01`
- `npm run server:api` inside **Sample-01**
- `npm start` inside **Sample-01**

The sample application has a protected route `http://localhost:4200/external-api` with a button to trigger a protected API that is served as part of `npm run server:api`.
Please let me know if and how you can reproduce the problem, it helps us to identify what is going wrong.

Can you also let me know what the expiration time of your tokens is? You can find this value in the target API settings inside Auth0:

![image](https://user-images.githubusercontent.com/2146903/104134326-24535c80-5389-11eb-80fd-2f184d8e5717.png)

I will reopen the issue in the meantime, but keep in mind that the error you are seeing is expected in some situations when using Incognito and you will need to handle that error yourself as mentioned above.

**Comment by JacekKruzel** [comment] 2021-01-11 11:37
Thank you for your quick response. 

I managed to reproduce a problem in a trivial angular app and narrow conditions down.

To reproduce the issue authService's _.getAccessTokenSilently()_ must be called in constructor of the service, that is used in angular's APP_BOOTSTRAP_LISTENER (on localhost while beeing in incognito mode).

Provider:
```
export const MY_CUSTOM_PROVIDER = {
    provide: APP_BOOTSTRAP_LISTENER,
    multi: true,
    useFactory: MY_CUSTOM_FN,
    deps: [SERVICE_THAT_CALLS_getAccessTokenSilently_IN_CONSTRUCTOR]
} as Provider;
```


Service:
```
@Injectable({providedIn: 'root'})
export class Heap {

    constructor(private _authService: AuthService) {

        this._authService.isAuthenticated$.subscribe(ia => console.log(ia)); // !!THIS IS TRUE!

        this._authService.getAccessTokenSilently().subscribe(t => console.log(t), e => {
            this._authService.loginWithRedirect(); // even though isAuthenticated is true, the error occurs. this will cause infinite loop.
        });
    }
}
```



The call to getAccessTokenSilently triggers the error in the console and results in error for the app (ie. httoclient will not perform any authorized calls).

Please also note, that the errors says "Login required" even though isAuthenticated$ subscribtion prints **true**.

Calling loginWithRedirect() is not an option - user already is logged in (the error is cause by something else despite the message), so this will cause infinite login loop. 


We have a need of triggering analytical tools as early in the app lifecycle as possible. Botstrap listeners are a perfect fit for us.

**Comment by frederikprijck** [comment] 2021-01-11 13:49
> Please also note, that the errors says "Login required" even though isAuthenticated$ subscribtion prints true.

There is a difference between those two things. "Login required" means that Auth0 is telling us the current user is not authenticated with Auth0 while `isAuthenticated$` means we have a token/user clientside.

In this case, Login required is happening because of iframes being used while that is not supported in Incognito.

I have been able to reproduce your steps and see the error occur, however this seems to behave as expected.

What's happening is that you are trying to use getAccessTokenSilently to retrieve a token using iframes in Incognito modus. As I mentioned earlier, this is not supported.

An `APP_BOOTSTRAP_LISTENER` (or `APP_INITIALIZER`) is executed before our SDK has been able to exchange the `Authorization Code` for an `Access Token`. This means that every time you call `getAccessTokenSilently` in your code, the SDK has no Access Token (yet) and it is forced to silently request the Access Token from Auth0 instead of pulling it from the internal cache. However, as I mentioned, this is not supported in Incognito Modus because of browser limitations.

In order to make your example work, you could do the following:

- Configure AuthModule to use local storage:
```
AuthModule.forRoot({
      cacheLocation: 'localstorage'
    }),
```
- Keep the loginWithRedirect in your service:
```
@Injectable({providedIn: 'root'})
export class Heap {

    constructor(private _authService: AuthService) {

        this._authService.isAuthenticated$.subscribe(ia => console.log(ia)); // !!THIS IS TRUE!

        this._authService.getAccessTokenSilently().subscribe(t => console.log(t), e => {
            this._authService.loginWithRedirect(); // even though isAuthenticated is true, the error occurs. this will cause infinite loop.
        });
    }
}
```

This will not result in an infinite loop anymore.
The reason why local storage makes it work is because now the access token is persisted between page reloads and on the second visit, our SDK has an Access Token available. When you do not use local storage, the access token is kept in memory and lost between page refreshes.

However, you should avoid calling `getAccessTokenSilently` in any `APP_BOOTSTRAP_LISTENER` provider, same for `APP_INITIALIZER`. You should only call `getAccessTokenSilently()` in places where you know a user is authenticated, e.g. by moving it inside a route that uses the AuthGuard. This should remove the need to use loc al storage, while you will still need to keep the error handler to redirect the user when Login required is thrown.

**Comment by JacekKruzel** [comment] 2021-01-14 15:22
> There is a difference between those two things. "Login required" means that Auth0 is telling us the current user is not authenticated with Auth0 while isAuthenticated$ means we have a token/user clientside.

Does this mean that **isAuthenticated**$ does not tell us wether user... **is authenticated**?
Also, how in above situation can we 
> have a token/user clientside

 and in the same time not be authenticated by Auth0?

> What's happening is that you are trying to use getAccessTokenSilently to retrieve a token using iframes in Incognito modus. As I mentioned earlier, this is not supported.

I'm fine with it not beeing supported. Saying that I would expect a library to have a proper fallback iframe -> full redirect, not a "Login required" message for user **who is logged in and already has a token**


> (1)you should avoid calling getAccessTokenSilently in any APP_BOOTSTRAP_LISTENER provider, same for APP_INITIALIZER. (2) You should only call getAccessTokenSilently() in places where you know a user is authenticated

From what I understand (1) **does not imply** that (2) is not not true.
I can **both** call getAccessTokenSilently in APP_BOOTSTRAP_LISTENER **and** be sure that user is authenticated. I know it from a observable provided by authService called isAuthenticated$. 

This is what I do:

```
    private _value = this._authService.isAuthenticated$.pipe(
        filter(ia => ia),
        switchMap(() => defer(() => this._authService.getAccessTokenSilently())),
        catchError(e => this._handleLoginRequired(e)),
        publishReplay(1)
    );

    private _handleLoginRequired(e: any): Observable<string> {
        return e.error === 'login_required' ?
            this._authService.loginWithRedirect().pipe(switchMapTo(NEVER)) :
            throwError(e);
    }
```

and i end up with infinite loop... 



Local Storage Cache is not an option for us as we need to be able to signe out user without him reaching SPA.

**Comment by frederikprijck** [comment] 2021-01-14 16:23
> Does this mean that isAuthenticated$ does not tell us wether user... is authenticated?

isAuthenticated tells us when we have a user in our Angular application, which is unrelated to whether we are authenticated with Auth0 (see below). In my case this is not showing `true` when redirecting to Auth0.

Keep in mind isAuthenticated can be true, when the token is expired. In that case it will redirect to Auth0 and come back to your application.

So isAuthenticated from an SPA perspective means that we have been authenticated with Auth0 before, and that we most likely still are. But other parts in the SDK might detect an expired token and try to refresh the token. isAuthenticated shows true in this case because, having an expired token might still mean you are authenticated.

> Also, how in above situation can we have a token/user clientside and in the same time not be authenticated by Auth0?

This is basically the concept of using OAuth's Authorization Code Grant. Let's take the following use case:

- A user logs in to Auth0, Auth0 creates a session for that user on the Auth0 domain. Lets say this session lasts 30 minutes. This means the user will stay logged in with Auth0 for 30 mins.
- your application requests a token for that user, the token is valid for 2 hours.
- After 30 mins, the user will not be authenticated with Auth0, but they will still have a token that is valid for another 1,5 hours.
- Even more so, even we start using Refresh Tokens, a user can keep using tokens for days, weeks or months, without ever needing to reauthenticate to Auth0.

So in the above use case you can see, once you have a token, that token is valid until it is expired. This is unrelated to being authenticated with Auth0 (or any other identity provide, this is how OAuth works).

Now let us take the following scenario:

- A user logs in to Auth0, Auth0 creates a session for that user on the Auth0 domain. Lets say this session lasts 60 minutes. This means the user will stay logged in with Auth0 for 30 mins.
- your application requests a token for that user, the token is valid for 30 minutes.
- After 30 mins, the token will expire. isAuthenticated will still be true, but our SDK will try to request a new token.
- In normal situations the above works fine because the user still has a cookie with Auth0 that is valid for another 30 minutes. However, in Incognito this will throw a login_required error, as our SDK is unable to use iframes to refresh the token because of the fact that incognito blocks 3rd party cookies. This error is something we do not handle internally in the SDK, as mentioned below.

This second use case is one of the typical situations where you will see `isAuthenticated$` being true, but you will also see a `login_required` message. This is one of the weird behaviors related to incognito. As mentioned in a linked comment above, our SDK is known to behave like this in cognito. 

> I'm fine with it not beeing supported. Saying that I would expect a library to have a proper fallback iframe -> full redirect, not a "Login required" message for user who is logged in and already has a token

Our library does not handle the redirect for you. As I mentioned, this is something the user of the SDK should handle. The reason for this is because not all applications have the same requirements when it comes to handling the `login_required` error. Also, as mentioned earlier, you are hitting the error most likely due to incognito, which is known to cause login_required.

> (1)you should avoid calling getAccessTokenSilently in any APP_BOOTSTRAP_LISTENER provider, same for APP_INITIALIZER. > > (2) You should only call getAccessTokenSilently() in places where you know a user is authenticated

When you load an SPA without using local storage, we have no information of the user initially (because when u keep everything in memory, you lose everything when u refresh). This means we need to check with Auth0, in an asynchronous way, if there is a user known with Auth0. If not, the user should Authenticate. Obviously, this process can not happen before Angular is fully bootstrapped and initialized, therefor you should not call `getTokenSilently` in both the `APP_BOOTSTRAP_LISTENER` or `APP_INITIALIZER` as it is expected for the SDK to not be finished initializing and retrieving user information from Auth0. 

Even more so, our SDK has an `isLoading$` observable that can be used to verify if the SDK has finished loading. Only once it is finished should you be able to use our SDK. Again, this is due to the above mentioned asynchronous nature of securing Single Page Applications.

If you do want to use `APP_BOOTSTRAP_LISTENER` or `APP_INITIALIZER`, you can work around it by using local storage. Even tho that will still involve weird behavior, it will get rid of the infinite loop.

> Local Storage Cache is not an option for us as we need to be able to signe out user without him reaching SPA.

If you call `AuthService.logout()`, our SDK will also clear local storage for you.

> This is what I do:
> ```
>    private _value = this._authService.isAuthenticated$.pipe(
>        filter(ia => ia),
>        switchMap(() => defer(() => this._authService.getAccessTokenSilently())),
>        catchError(e => this._handleLoginRequired(e)),
>        publishReplay(1)
>    );
>
>    private _handleLoginRequired(e: any): Observable<string> {
>        return e.error === 'login_required' ?
>            this._authService.loginWithRedirect().pipe(switchMapTo(NEVER)) :
>            throwError(e);
>    }
>```
>and i end up with infinite loop...

This isn't working at all for me. Not even is it giving me an infinite redirect, but it is also never getting to `isAuthenticated$` to emit `true`, I am always seeing `false`.
Can you please provide a reproduction sample? It would make it a lot easier for us to look into. I will reopen this and look into your reproduction sample once provided.

But please keep in mind what I mentioned above and the fact that these kind of things are not supposed to be called from inside an `APP_BOOTSTRAP_LISTENER` in Angular. Even tho we might get it to work, from an Angular perspective, this isnt expected that you use the BOOTSTRAP_LISTENER for these kinds of things.

**Comment by frederikprijck** [comment] 2021-03-11 09:10
Closing this as there haven't been any reply and I believe this works as intended.

**Closed as completed by frederikprijck** 2021-03-11 09:10 UTC
Labels: question

**Comment by binod009** [comment] 2024-07-11 08:36
![Uploading ERROR.png…]()
am also facing the same error in reactjs, however the sample project provided by the auth0 i have tried and did not got error one reason could be that the sample project provided by auth0 has same route like localhost:3000  where the main page ,login page is but developer ususally do't do that they have different url for login and main page and i have exaclty setup that way for login its localhost:5173/login and for main page after loggedin localhost:5173, whereas when i see the documentation of auth0 they teach me to keep the url same for the three field i.e callbackurl,allowed web origin and logout url but this is not supposed to happen?
