### ISSUE TITLE
isAuthenticated$ Observable is getting false after successfull login.

### ISSUE THREAD

**Issue by sayemuddinkhan-mriirs** [auth0/auth0-angular#217] opened 2021-09-16 13:36 UTC
Hello , I am integrating auth0 universal login page into my existing application in angular but after successfully login I am getting "isAuthenticated$" value "false" . I have checked and explored many docs and issues on the web but none of them helped me . Is there anything to get it true after login.

I am using below versions:-
1.) Angular CLI - 11.1.0
2.) auth0 sdk - 1.6.0 (Alsoused 1.6.1 earlier, but nothing happened)

I am a newbie to auth0 and really cant getmyself out of this , any solution/help will much appreciated.

Thank you :)

**Comment by frederikprijck** [comment] 2021-09-16 14:13
A little bit hard to know exactly what is going on with this information.
I would advise you to create a reproduction of the problem so we can have a look at what is going on and help you get it working.

One thing I can think of is, did you inject the Auth0Service in your AppComponent?

**Comment by sayemuddinkhan-mriirs** [comment] 2021-09-16 14:41
Yes I injected the Auth0 service in my constructor. Actually I am following the sample example of angular quickstart app to integrate login logout in my app but couldn't get success. On 16-Sep-2021 7:43 pm, Frederik Prijck ***@***.***> wrote:
A little bit hard to know exactly what is going on with this information.
I would advise you to create a reproduction of the problem so we can have a look at what is going on and help you get it working.
One thing I can think of is, did you inject the Auth0Service in your AppComponent?

**Comment by sayemuddinkhan-mriirs** [comment] 2021-09-17 12:59
Heyy @frederikprijck , I am following this tutorial [Angular Quickstart](https://auth0.com/docs/quickstart/spa/angular?download=true). But when I logs in , I am not getting **isAuthenticated$** observable value as true instead its always giving me false.

**Comment by frederikprijck** [comment] 2021-09-17 13:42
@sayemuddinkhan-mriirs ,

Sorry, I can not reproduce that behavior. Could you provide the application that isn't working so we can look into what is causing this?

Thanks.

**Comment by gravy-11** [comment] 2021-09-25 08:54
@sayemuddinkhan-mriirs 

I had the same problem. 
But I noticed I didn't select the Application Type.

I overlooked the following note in the tutorial([Angular Quickstart](https://auth0.com/docs/quickstart/spa/angular?)).

> When using the Default App with a Native or Single Page Application, ensure to update the Token Endpoint Authentication Method to None and set the Application Type to either SPA or Native.

I don't know if it is the cause of your problem or not, but I hope this helps you.

**Comment by frederikprijck** [comment] 2021-09-27 12:24
Closing this as there hasn't been any response. Feel free to reply if there is anything you think we should be looking into!

**Closed as completed by frederikprijck** 2021-09-27 12:24 UTC
Labels: question, need more info
