### ISSUE TITLE
[auth0/ionic-angular] Starter project isn't behaving as intended

### ISSUE THREAD

**Issue by Ookamini95** [auth0/auth0-angular#499] opened 2023-09-27 13:59 UTC
### Checklist

- [X] The issue can be reproduced in the [auth0-angular sample app](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

After setting up the base ionic-angular project with auth and Google login as per the Auth0 Ionic & Capacitor (Angular) SDK Quickstarts, I'm encountering multiple issues related to login behavior on various devices and simulators. I expected the login to work as described in the documentation.

Behavior Observed
    Gets stuck after pressing login on Xiaomi M2007J3SY + Chrome. Works with "Mi Browser" but then gets stuck after Google login.
    Gets stuck after Google login on simulator and browser. It redirects to callback?code={code} and fails to load the page.
    After Google login, redirects to /home but doesn't display any user information, and has a token in the network tab.
    Login page (auth + google login page) is skipped and goes directly to /home with a 401 token in the network tab

### Reproduction

1. Clone the base ionic-angular project.
2. Configure the app settings via the Auth0 dashboard.
3. Either run `npm i && npm run build && npx cap run android` or `npm i && npm run build && ionic serve -p {PORT}`

### auth0-angular version

2.2.0

### Angular version

15.1.1

### Which browsers have you tested in?

Chrome, Other

**Comment by frederikprijck** [comment] 2023-09-28 07:20
Thanks for reaching out. Unfortunatly, I was unable to reproduce this using the latest https://github.com/auth0-samples/auth0-ionic-samples/tree/main/angular, it works as expected both when using username+password login as well as google login.

What emulator are you using and what android version?

**Comment by frederikprijck** [comment] 2023-10-09 07:56
Closing, feel free to ping me with the info requested and we can reopen.

**Closed as completed by frederikprijck** 2023-10-09 07:56 UTC
Labels: bug, need more info
