### ISSUE TITLE
Auth0-Angular is not working fine with Angular SSR Universal

### ISSUE THREAD

**Issue by rohithart** [auth0/auth0-angular#305] opened 2022-05-04 22:08 UTC
### auth0-angular and Angular Universal

> I understand that the Angular universal error `ReferenceError: window is not defined` has been addressed by both Angular as well as `auth0-angular` and [this](https://github.com/auth0/auth0-angular#angular-universal) in angular-universal docs. I now understand the issue and that there is a solution for it, that has been acknowledged by both the libraries, however I find it hard to implement. I was wondering if there are some sample implementation for the same, or if there is anyone who has already done this?

I have raised the same in [stackoverflow](https://stackoverflow.com/questions/72012878/auth0-angular-is-not-working-fine-with-angular-ssr-universal)

**Comment by frederikprijck** [comment] 2022-05-05 07:43
Hey,

To use SSR with any library that uses window, you want to look into [Angular Universal's Guard pattern](https://github.com/angular/universal/blob/main/docs/gotchas.md#strategy-2-guards).

In our case, you want to not import AuthModule on the server, but provide mock implementation for our AuthService to ensure it doesn't try and access window on the server.


```ts
// fake-auth.service.ts
import { Injectable } from '@angular/core';
import { AuthService } from '@auth0/auth0-angular';

@Injectable()
export class FakeAuthService extends AuthService {
  handleRedirectCallback(
    url?: string
  ): Observable<RedirectLoginResult> {
    return of({});
  }
}
```
You can override any method that is causing issues above.
Then ensure to provide this correctly to the module used to bootstrap the app on the server.
```ts
// app-server.module.ts
import {NgModule} from '@angular/core';
import {AuthService} from '@auth0/auth0-angular';
import {FakeAuthService} from './fake-auth.service';

@NgModule({
  providers: [{
    provide: AuthService,
    useClass: FakeAuthService,
  }]
})
```

Would that help ?

**Comment by rohithart** [comment] 2022-05-05 11:05
Hi @[frederikprijck](https://github.com/frederikprijck)
This was of great help, now `yarn run dev:ssr` works, however I am getting this error:
```
Error: For security reasons, `window.crypto` is required to run `auth0-spa-js`.
    at /Users/user/angular-ssr/dist/grocery/server/main.js:19308:24
    at new e (/Users/user/angular-ssr/dist/grocery/server/main.js:19310:6)
    at Object.createClient [as useFactory] (/Users/user/angular-ssr/dist/grocery/server/main.js:14840:16)
    at Object.factory (/Users/user/angular-ssr/dist/grocery/server/main.js:204927:38)
    at R3Injector.hydrate (/Users/user/angular-ssr/dist/grocery/server/main.js:204843:35)
    at R3Injector.get (/Users/user/angular-ssr/dist/grocery/server/main.js:204662:33)
    at injectInjectorOnly (/Users/user/angular-ssr/dist/grocery/server/main.js:198151:33)
    at Module.ɵɵinject (/Users/user/angular-ssr/dist/grocery/server/main.js:198155:61)
    at AuthService_Factory (/Users/user/angular-ssr/dist/grocery/server/main.js:15347:138)
    at Object.AuthServerService_Factory [as factory] (/Users/user/angular-ssr/dist/grocery/server/main.js:445:301)
```

Here is my `app.module.ts`.
```
@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule.withServerTransition({ appId: 'serverApp' }),
    AppRoutingModule,
    BrowserAnimationsModule,
    HttpClientModule,
    FlexLayoutModule,
    MaterialModule,
    SharedModule,
    ToastrModule.forRoot(),
  ],
  providers: [
    Meta,
    { provide: APP_CONFIG, useValue: AppConfig },
    { provide: HTTP_INTERCEPTORS, useClass: TokenInterceptor, multi: true }

  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

Here is my `app.server.module.ts`.
```
@NgModule({
  imports: [
    AppModule,
    ServerModule,
    FlexLayoutServerModule,
    AuthModule.forRoot({
      domain: environment.auth0.domain,
      clientId: environment.auth0.client_id,
      audience: `https://${environment.auth0.domain}/api/v2/`,
      useRefreshTokens: true,
      cacheLocation: 'localstorage',
      scope: 'offline_access',
      httpInterceptor: {
        allowedList: [
          '/api/*',
        ],
      },
		  }),
  ],
  providers: [{
    provide: AuthService,
    useClass: AuthServerService,
  }],
  bootstrap: [AppComponent],
})
export class AppServerModule {}
```

BTW, I have added the following in `server.ts` as well.
```
const domino = require('domino');
  const fs = require('fs');
  const path = require('path');
  const template = fs.readFileSync(path.join(__dirname, '..', 'browser', 'index.html')).toString();
  const win = domino.createWindow(template);
  global['window'] = win;
  global['document'] = win.document;
```
Any help is appreciated.

**Comment by frederikprijck** [comment] 2022-05-05 13:17
I think the idea is to not import `AuthModule` in the server module, would that help?

**Comment by rohithart** [comment] 2022-05-05 21:42
I tried that as well, AuthModule staying inside `app.module.ts`. However the issue still remain.
This is `auth.server.service.ts`
```
@Injectable()
export class AuthServerService extends AuthService {
  handleRedirectCallback(
    url?: string
  ): Observable<any> {
    return of({});
  }
}
```
Am I missing something? Any help is appreciated.
Similar to https://github.com/auth0/auth0-spa-js/issues/522 . Can provide more info if required.

**Comment by frederikprijck** [comment] 2022-05-06 07:08
Could u share a reproduction for us to look into? A github repository would be idea? Happy to look into it.

**Comment by rohithart** [comment] 2022-05-08 10:20
Hi mate, here is a repo. https://github.com/rohithart/angular-auth0-ssr
I have a sample app in here, where in I just added Angular universal and the solution that you provided. `yarn dev:ssr` fails.
Any help is appreciated.

**Comment by frederikprijck** [comment] 2022-05-09 07:03
Please do not import `AuthModule` in the server. It is still getting imported because u have: `AppServerModule` which imports `AppModule` which imports `AuthModule`. You want to ensure AuthModule is **not** imported in the server, you can do this by making a `AppClientModule`, which imports both `AppModule` and `AuthModule`, and remove `AuthModule` from `AppModule`. 

I tested the above in your repository and it works.

Closing, as this isn't related to our SDK but more to how to set up SSR correctly which I believe this repository isn't the best place.

**Comment by rohithart** [comment] 2022-05-09 20:08
> Please do not import `AuthModule` in the server. It is still getting imported because u have: `AppServerModule` which imports `AppModule` which imports `AuthModule`. You want to ensure AuthModule is **not** imported in the server, you can do this by making a `AppClientModule`, which imports both `AppModule` and `AuthModule`, and remove `AuthModule` from `AppModule`.
> 
> I tested the above in your repository and it works.
> 
> Closing, as this isn't related to our SDK but more to how to set up SSR correctly which I believe this repository isn't the best place.

After your above suggestion `NullInjectorError: No provider for InjectionToken auth0.client!` is the error. I have updated my repo.

**Comment by frederikprijck** [comment] 2022-05-10 07:55
I opened a PR on your repository to fix this, see https://github.com/rohithart/angular-auth0-ssr/pull/1

![image](https://user-images.githubusercontent.com/2146903/167577758-175582fd-6dfb-4780-9c6a-1621c94baec3.png)

Do note that I had to disable the CSP, as that made the requests fail with

> Refused to connect to 'https://[domain].eu.auth0.com/oauth/token' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' 'unsafe-eval'

You might want to ensure the CSP is configured correctly to allow our SDK to function.

**Closed as completed** 2022-06-01 12:55 UTC
Labels: feature request
