### ISSUE TITLE
Need to refresh to be considerate as authenticated

### ISSUE THREAD

**Issue by BrunoBeraudPW** [auth0/auth0-angular#87] opened 2020-11-18 11:04 UTC
### Describe the problem

Hi !

I have a trouble which I can reproduce with the playground application.

I have two apps : domain1 and domain2 (this last one are your playground application).
There are all configured on the same auth0 domain.

I have to use getAccessTokenSilently() method on domain2 to be authorized to use my API.

When I'm authenticated on domain1 and I want to access to domain2,
I'm first considerate as unauthenticated by the package, which is not good.
But when I refresh the page I'm finally considerate as authenticated.

### What was the expected behavior?

I should not have to refresh the page of domain2 to be authenticated.

### Reproduction

1. I'm connected to domain1 with auth0
2. I want to access to domain2 as user authenticated of domain1
3. I'm accessing to domain2 but the authService.isAuthenticated$ considers me as unauthenticated.
4. I'm doing in parallel getAccessTokenSilently to get token for my API, I'm still unauthenticated
5. I refresh the page, I'm finally considered as authenticated

I have maybe a solution, in the service auth.service.ts we have this
```
 const checkSessionOrCallback$ = (isCallback: boolean) =>
      iif(
        () => isCallback,
        this.handleRedirectCallback(),
        defer(() => this.auth0Client.checkSession())
      );
```

We could have this, and it's working in my case :

```
 const checkSessionOrCallback$ = (isCallback: boolean) =>
      iif(
        () => isCallback,
        this.handleRedirectCallback(),
        defer(() => this.auth0Client.getTokenSilently())
      );
```
But I'm not sure it's a good solution.

Or, when we use the method of this same service getAccessTokenSilently, and if it successful, we could emit true on the Subject isAuthenticatedSubject$, so that we are authenticated now.

What do you think ?

### Environment

The current playground application, with Chromium and Firefox.

**Comment by frederikprijck** [comment] 2020-11-18 11:33
Thanks for raising this. 

> Or, when we use the method of this same service getAccessTokenSilently, and if it successful, we could emit true on the Subject isAuthenticatedSubject$, so that we are authenticated no.

I think this could be a good idea. Let me open up a conversation internally around this and get back to you.

I do want to add that this is a bit of a special case as well, as I would argue your application should rely on `isAuthenticated` _before_ calling `getTokenSilently`. I mean, why would you allow someone to request a token if they are not authenticated (sure, they are authenticated on a different tab, but it is weird by design to allow someone to request a token if they are not authentivated in the current process)?

**Comment by jreilly-lukava** [comment] 2020-11-23 22:58
@frederikprijck I'm a novice at this stuff, but isn't that kind of what Google does if you open up new tabs to new apps.  I realize under the hood may be different.  But my use case would be to authenticate to one application in my domain and then be automatically authenticated to other apps in my domain as soon as I open them without having to click a login button or anything.

**Comment by frederikprijck** [comment] 2020-11-24 10:42
@jreilly-lukava 

The following works fine:

- open app1.domain.com and click login to authenticate yourself
- open app2.domain.com and be automatically logged in without any need to click login

What doesnt work is the following:

- open app1.domain.com 
- open app2.domain.com (so open the second app before being authenticated in any of the two apps)
- Click login on app1.domain.com to authenticate yourself
- app2.domain.com will still show the login button and not automatically pick up you are authenticated unless you either click login or refresh the page.

This behavior is comparable to popular application such as google and facebook.

**Comment by frederikprijck** [comment] 2021-01-04 08:30
As this behavior is expected, I am closing this issue. Feel free to continue the conversation if you believe otherwise.

**Closed as completed by frederikprijck** 2021-01-04 08:30 UTC
Labels: question
