### ISSUE TITLE
AuthService is intercepting calls that are not meant for it

### ISSUE THREAD

**Issue by Boomwav** [auth0/auth0-angular#94] opened 2020-12-02 17:04 UTC
### Describe the problem you'd like to have solved

In my application, I am using both @auth0/auth0-angular and angular-oauth2-oidc. Auth0 for external clients and oauth2 for internal clients. My problems arrives when I try to inject auth0-angular AuthService in my interceptor. Now, whenever I try to get a callback for internal clients (that should be answered by angular-oauth2-oidc, Auth0 will try to capture it and return to "/".. triggering an authentication loop. If I don't use AuthService and instead use the official interceptor, everything runs fine. 

### Describe the ideal solution

Add more checks to make sure the callback is meant for Auth0. Or add a config so that we can control what happened in case an error happened. Personally, I'd prefer if the callback was not answered by Auth0 if it's not meant for it. Maybe it could check if the origin match the expected URL?

## Alternatives and current work-arounds

The current workaround is to use the official interceptor and never inject AuthService in an interceptor.

**Comment by frederikprijck** [comment] 2020-12-02 17:07
Thanks for reporting, We merged a PR to fix this a few minutes before this being reported so it should be resolved in the next release. Could you have a look if the merged PR would resolve your use case? If not we can reopen this issue, but closing for now.

Duplicate of https://github.com/auth0/auth0-angular/issues/83, resolved by https://github.com/auth0/auth0-angular/pull/86.

**Closed as completed by frederikprijck** 2020-12-02 17:07 UTC
Labels: duplicate, feature request
