### ISSUE TITLE
Accuracy and Reliability of isAuthenticated

### ISSUE THREAD

**Issue by marc-wilson** [auth0/auth0-angular#508] opened 2023-10-09 22:48 UTC
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

`ERROR Error: External interaction required` errors are extremely frequent and predictable but are not preventable. Since `isAuthenticated$` only checks to see if something is _present_ in the cache rather than checking if the user is authenticated, it's a guarantee this error will be thrown for any returning user. In my case, my logs are riddled with the error and `isAuthenticated$` should give you the tools to actually prevent it from happening in the first place.

```
const accessToken$ = this.auth0.isAuthenticated$.pipe(
  filter((isAuthenticated) => isAuthenticated),
  map( () => this.auth0.getTokenSilenty())
)
```

In this code, the problem child is the logic around `isAuthenticated$`. This observable returns true if there is a token present in the cache, not if the user is actually authenticated.

This is a problem because the next time the user visits the page, their expired token is in the cache. This means that `isAuthenticated` is `true` and therefore, `getAccessTokenSilently` runs and throws the above error.

We've had to setup additional logic for our monitoring systems to disable any on call alerts for the error since it's very frequent and expected.

### Describe the ideal solution

- `isAuthenticated$` should check for the presence of a token **and** it's expiration.
- Add a method to the package that allows the developer to fetch the toke _from the cache_ so that it can be manually parsed/checked to prevent any downstream calls that will fail due to token expiration or validity.
- The _ideal_ solution would be to make it so `isAuthenticated$` holds an accurate value (the user is authenticated or not).

### Alternatives and current workarounds

I want to try and obtain the token from the cache to manually check the expiration, but I'm not seeing any OOTB method for that. The key used in (local storage) doesn't look reliable enough to simply look it up every time and compare the expiration time alongside the value of `isAuthenticated`.

Any input/advice on how to easily obtain the current jwt in the cache in a reliable form would be greatly appreciated.

### Additional context

There is also documentation around using `isAuthenticated` in angular guards to protect sensitive routes. I would argue checking for the presence of something is not the correct method here.

**Comment by marc-wilson** [comment] 2023-10-09 23:07
Reading through the code, I found a setting called `cacheMode` that can be passed with `getTokenSilently`.

```
  /**
   * When `off`, ignores the cache and always sends a
   * request to Auth0.
   * When `cache-only`, only reads from the cache and never sends a request to Auth0.
   * Defaults to `on`, where it both reads from the cache and sends a request to Auth0 as needed.
   */
  cacheMode?: 'on' | 'off' | 'cache-only';
```

So, I'm assuming simply configuring that to be `on` does what I want.

**Comment by marc-wilson** [comment] 2023-10-09 23:09
Reading through the code in `getAccessTokenSilenty`, there's an option for `cacheMode`

```
  /**
   * When `off`, ignores the cache and always sends a
   * request to Auth0.
   * When `cache-only`, only reads from the cache and never sends a request to Auth0.
   * Defaults to `on`, where it both reads from the cache and sends a request to Auth0 as needed.
   */
  cacheMode?: 'on' | 'off' | 'cache-only';
```

Is there some similar concept for `isAuthenticated$`?

**Comment by frederikprijck** [comment] 2023-10-10 04:58
No, there is no such option.

Additionally, isAuthenticated should not take any expiration into account. [Here](https://github.com/auth0/auth0-spa-js/blob/main/FAQ.md#why-is-isauthenticated-returning-true-when-there-are-no-tokens-available-to-call-an-api) is an explanation of isAuthenticated, hopefully that help explain why. But as you can see its intentional.

However, we do want to prevent any unexpected errors, can you elaborate on how to reproduce?

If you want to build your own logic that does include the expiration, that's ofcourse something you can do, but not something we will add to the SDK. I recommend not using isAuthenticated, but build your own isAuthorized (or hasTokenForApi) that uses the response of `getAccessTokenSilently({ detailedResponse: true, cacheMode: 'cache-only' })`. Passing detailedResponse ensures it returns an expires_in as well that you can use. (You might not even need that and only use cacheMode)

**Comment by frederikprijck** [comment] 2023-10-10 05:07
No, there is no such option.

Additionally, isAuthenticated should not take any expiration into account. [Here](https://github.com/auth0/auth0-spa-js/blob/main/FAQ.md#why-is-isauthenticated-returning-true-when-there-are-no-tokens-available-to-call-an-api) is an explanation of isAuthenticated, hopefully that help explain why. But as you can see its intentional.

However, we do want to prevent any unexpected errors, can you elaborate on how to reproduce?

**Comment by marc-wilson** [comment] 2023-10-10 18:23
Thanks for the information. Taking a step back to the root issue, is my understanding of `getAccessTokenSilenty` correct? Meaning that if there is an expired token present in the cache, `getAccessTokenSilently` will throw the error `ERROR Error: External interaction required`?

From what you've outlined, `isAuthenticated` doesn't sound like the tool that I'm after. If the error is in fact supposed to be getting thrown in the scenario outlined above, are you proposing i do something like the following?

```
const cachedToken = await this._getAcccessTokenSilently({ detailedResponse: true, cacheMode: 'cache-only' });
if (cachedToken is not expired)
    const remoteToken = await this._getAccessTokenSilenty();
else
    login
```

**Comment by frederikprijck** [comment] 2023-10-10 18:32
Regarding `External interaction required`, I recommend https://community.auth0.com/t/external-interaction-required-error-appears-during-silent-authentication/106026.

I assume there is a rule at play, and I advice you to take a look at the rule and see how things behave with or without.

> Meaning that if there is an expired token present in the cache, getAccessTokenSilently will throw the error ERROR Error: External interaction required?

So to reply to that, no that is not supposed to happen and is caused by an (possibly incorrectly configured) rule. getAccessTokenSilently will try to get a token from the cache, and if it can not fine one it will call Auth0 with prompt=none (which is what we call silent auth). I assume this is triggering a rule or something that is resulting in the error.

You can see that in the Network tab and inspect what error you get back from Auth0. Our SDK just passes that error through to the developer, but doesn't throw such an error itself.

> From what you've outlined, isAuthenticated doesn't sound like the tool that I'm after. If the error is in fact supposed to be getting thrown in the scenario outlined above, are you proposing i do something like the following?

Based on the link I shared, you either want to avoid the error by fixing the rule (which I think u want anyway, you can detect silent auth if `prompt=none` is present in the query). If you can not do that, then I think you want:

```ts
try {
  const token = await client.getAcccessTokenSilently();
} catch (e) {
  client.loginWithRedirect(); // Probably only when its the error you mentioned above
}
```

I don't think you need to worry about using `cacheMode` or `detailedResponse`. Either fix the rule, or catch the error as per the community link above.

Closing as I think this is outside of the scope of the SDK, but feel free to continue the conversation and I can always see where I can assist further.

**Closed as completed by frederikprijck** 2023-10-10 18:32 UTC
Labels: feature request

**Comment by marc-wilson** [comment] 2023-10-10 23:56
Thanks, @frederikprijck. We do in fact have an action in place (post login) that redirects the user to an intermediary page and once done, continues the auth flow.

I did what you suggested and checked the query in the action to see if `prompt === 'none'`. I did a quick test by just short circuiting the rule and bailing out if `prompt === 'none'`. Once I did that, the error is gone and the user is properly redirected to the login page.

To make sure my understanding is correct, the sequence of events is this

- User revisits page with an expired token
- `getAccessTokeSilently` gets called
- `getAccessTokeSilently` see's the token is expired so it fetches a new one which kicks off our entire auth flow and namely our action that is doing a redirect.
- Since during the silent auth, we try and do a redirect, we get the error stating that login/external interaction is required.
- Implementing logic to not do the redirect in the auth action if `prompt === 'none'` prevents the redirect from happening so no error is generated.
- Since you cannot do a redirect during silent auth, we need to handle the response and act accordingly.

It's a little odd for us since our post login event does some stuff to add claims to the accessToken and our application won't allow the user in without it. So when I implement the conditional logic to not redirect during silent auth, `getAccessTokenSilently` actually succeeds and returns an updated token that isn't expired. But, we are obviously missing our claims in the access token since the auth action didn't do the redirection to collect the data from the user we need.

**Comment by frederikprijck** [comment] 2023-10-11 04:54
> To make sure my understanding is correct, the sequence of events is this

Everything said above is correct. I understand the issue with missing claims in that case. That does go beyond the scope of our SDK.

You would have the same issue when using refresh tokens...

Both silent auth and refresh tokens are concepts of auth0 server, and not our SDK. I recommend to reach out to your account manager to get in touch with someone to help figuring out a solution for your action to work well with both silent auth and refresh tokens, or see how you can add claims without requiring a redirect yourself.
