### ISSUE TITLE
isAuthenticated always returns false because of shareReplay

### ISSUE THREAD

**Issue by YassinHajaj** [auth0/auth0-angular#447] opened 2023-04-18 16:37 UTC
### Describe the problem

> Provide a clear and concise description of the issue

When using `authService.isAuthenticated$`, the value `false` is always returned.

The problem might be a side effect of [PR 209](https://github.com/auth0/auth0-angular/pull/209) (Do not redirect AuthGuard when user is already  authenticated).

This line has been added, which probably only computes the value once and keeps on returning it, not bothering with reevaluating it.

```
  readonly isAuthenticated$ = this.isAuthenticatedTrigger$.pipe(
    distinctUntilChanged(),
    shareReplay(1) // <------ THIS ONE
  );
```

### What was the expected behavior?

> It should be clear whether the user is logged in or not. And workarounds are not a valid solution.

### Reproduction

The sample app should normally provide the expected behaviour

### Environment

- Version : "@auth0/auth0-angular": "^2.1.0"
- Browser : Google Chrome
- Angular 15

I could help work on a fix if the fix is straightforward (because I'm not a frontend developer)

**Comment by frederikprijck** [comment] 2023-04-18 21:44
Thanks for reaching out.

I can't reproduce this as I can see isAuthenticated is true when I'm logged in. Can you elaborate on what you are doing to reproduce this, as well as why you think it shouldn't return false?

**Comment by YassinHajaj** [comment] 2023-04-18 21:46
Hello Frédéric,

Thanks for the quick answer, I'll try to reproduce it tomorrow with a small project.

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by frederikprijck** [comment] 2023-05-08 08:25
Closing, let me know if you still need help.

**Closed as completed by frederikprijck** 2023-05-08 08:25 UTC
Labels: need more info, bug report

**Comment by restfulhead** [comment] 2023-07-18 23:34
@frederikprijck I'm facing the same issue using https://github.com/auth0-samples/auth0-angular-samples. When I log in and then refresh the page, `AuthService.isAuthenticated$` first emits `false` and then after a few seconds `true`. This is frustrating, because the UI briefly shows the login link and then replaces it with the user profile.

**Comment by frederikprijck** [comment] 2023-07-19 05:19
@restfulhead please open another issue and provide something to reproduce. As mentioned above, i have not been able to reproduce this, but happy to look into this if you can help me reproduce it.

**Comment by restfulhead** [comment] 2023-07-19 22:06
> @restfulhead please open another issue and provide something to reproduce.

Ok, here you go: https://github.com/auth0/auth0-angular/issues/455
