### ISSUE TITLE
auth0 lock not initialized before auth.signin call yields error

### ISSUE THREAD

**Issue by schwer** [auth0/auth0-angular#260] opened 2016-05-12 14:15 UTC
I can reproduce the following error in firefox version 46.0.1 (though there is evidence this exists in other browsers).
With lock-9.1.4.min.js and angular-auth0-4.1.0.

I'm bundling all lock-9.1.4 and angular-auth0 with my own javascript.

To reproduce, restart firefox. Visit a page with the lock widget immediately after restarting. The issue goes away after a refresh. I believe it is caused by a race condition that may be difficult to reproduce outside of my environment.

I see 
![image](https://cloud.githubusercontent.com/assets/688963/15197153/e1740eb8-179d-11e6-8a0c-e67b076af764.png)

With the following error on the console:

```
TypeError: this.auth0Strategies is undefined
["/var/lib/jenkins/workspace/lock/lib/options-manager/index.js"]</</OptionsManager.prototype._getAuth0Connection()
 angular.js:33631
["/var/lib/jenkins/workspace/lock/lib/options-manager/index.js"]</</OptionsManager.prototype._isUsernameRequired()
 angular.js:33631
["/var/lib/jenkins/workspace/lock/lib/mode-signin/signin.ejs"]</anonymous/<()
 angular.js:33630
anonymous()
 angular.js:33630
["/var/lib/jenkins/workspace/lock/index.js"]</</Auth0Lock.prototype.render()
 angular.js:33627
["/var/lib/jenkins/workspace/lock/lib/mode-signin/index.js"]</SigninPanel.prototype.create()
 angular.js:33630
["/var/lib/jenkins/workspace/lock/lib/mode-signin/index.js"]</SigninPanel.prototype.render()
 angular.js:33630
["/var/lib/jenkins/workspace/lock/index.js"]</</Auth0Lock.prototype.setPanel()
 angular.js:33627
["/var/lib/jenkins/workspace/lock/index.js"]</</Auth0Lock.prototype._signinPanel()
 angular.js:33627
oninitialized()
 angular.js:33627
binded()
 angular.js:33628
finish()
 angular.js:33627
["/var/lib/jenkins/workspace/lock/index.js"]</</Auth0Lock.prototype.initialize()
 angular.js:33627
onoptionsready()
 angular.js:33627
binded()
 angular.js:33628
done()
 angular.js:33631
binded()
 angular.js:33628
g()
 angular.js:33635
["/var/lib/jenkins/workspace/lock/node_modules/browserify/node_modules/events/events.js"]</EventEmitter.prototype.emit()
 angular.js:33635
["/var/lib/jenkins/workspace/lock/lib/options-manager/index.js"]</</OptionsManager.prototype.state()
 angular.js:33631
["/var/lib/jenkins/workspace/lock/lib/options-manager/index.js"]</</OptionsManager.prototype._onclientloaded()
 angular.js:33631
binded()
 angular.js:33628
["/var/lib/jenkins/workspace/lock/index.js"]</</Auth0Lock.prototype.getClientConfiguration/<()
 angular.js:33627
g()
 angular.js:33635
["/var/lib/jenkins/workspace/lock/node_modules/browserify/node_modules/events/events.js"]</EventEmitter.prototype.emit()
 angular.js:33635
["/var/lib/jenkins/workspace/lock/index.js"]</</Auth0Lock.prototype.getClientConfiguration/global.window.Auth0.setClient()
 angular.js:33627
<anonymous>
 K5DD4oOuIPrJTKVSgYfBnDjNOdk8GzdZ.js:1
```

**Comment by schwer** [comment] 2016-05-12 14:18
I used the following workaround to solve the issue:

```
auth.config.auth0lib.once('client loaded', function(ignored) {
  auth.signin({
    gravatar: false,
    dict: dict,
    icon: loginLogoutServiceConfig.icon,
    closable: false,
    rememberLastLogin: false,
    ...
});
```

**Comment by schwer** [comment] 2016-05-12 16:33
To add more color- I'm calling the auth.signin function from an angular service immediately after angular loads- I don't load any directives or other resources prior to making the call. My guess is that the race condition does not manifest itself in those cases.

**Comment by christiannwamba** [comment] 2016-05-31 11:31
I guess this more of implementation concern. I believe it's not a bug as the expected behavior is to not call sign method on page load unless you listen to the `client loaded` event.

Thanks for the feedback. I will close this now but feel free to re-open if you need to.

**Closed by christiannwamba** 2016-05-31 11:31 UTC
