### ISSUE TITLE
Unable to sign in with token

### ISSUE THREAD

**Issue by jmls** [auth0/auth0-angular#191] opened 2015-12-23 17:42 UTC
I get an error when trying to refresh a page when a user is already signed in. I am following the example in step 

"7. Keep the user logged in after a page refresh" (https://auth0.com/docs/client-platforms/angularjs#7-keep-the-user-logged-in-after-a-page-refresh)

```
TypeError: Cannot read property 'getProfile' of undefined
    at Object.auth.getProfile (auth0-angular.js:417)
    at onSigninOk (auth0-angular.js:238)
    at Object.auth.authenticate (auth0-angular.js:414)
    at index.run.js:36
    at Scope.$broadcast (angular.js:16374)
    at angular.js:12335
    at Scope.$eval (angular.js:16052)
    at Scope.$digest (angular.js:15870)
    at Scope.$apply (angular.js:16160)
    at bootstrapApply (angular.js:1679)
```

Line 36 of my index.run.js is this

```
auth.authenticate(store.get('profile'), token);
```

and I have verified that both the token and profile are valid

If I use auth.profile I get null, and auth.isAuthenticated always returns false

I have tried with 4.0 and 4.1 of auth0-angular

**Comment by jmls** [comment] 2015-12-23 19:48
sorry to bump this, but I am trying to get the auth system working for a demo that I have in a few hours - I'm kinda stuck. I;ve tried looking at the code, but the proliferation of "this" throws me ;)

**Comment by jmls** [comment] 2015-12-28 18:02
*anyone* ?

**Comment by jmls** [comment] 2016-01-03 14:05
what do I need to do in order for someone to throw some light on this error ? Do a chicken-dance ? ;)

**Comment by maxlapides** [comment] 2016-01-14 22:00
I too am having this issue!

**Comment by dazaria** [comment] 2016-01-15 00:09
This issue is actually causing us a few headaches as well...

**Comment by maxlapides** [comment] 2016-01-27 23:47
After further investigation, I discovered that the reason why this wasn't working for me was I was attempting to execute `auth.authenticate()` before `authProvider.init()` was executed.

**Comment by christiannwamba** [comment] 2016-07-08 08:45
Hi. I will be closing this issue as it can't be reproduced. Please feel free to re-open if you have more information on this issue. Thank you

**Closed by christiannwamba** 2016-07-08 08:45 UTC
Labels: Unable to reproduce
