### ISSUE TITLE
It is not handling errors when user with lock.js and redirect mode.

### ISSUE THREAD

**Issue by glena** [auth0/auth0-angular#200] opened 2016-01-26 15:20 UTC
If it is being used with redirect mode:

```authProvider.init({
    domain: AUTH0_DOMAIN,
    clientID: AUTH0_CLIENT_ID,
    loginUrl: '/login',
    callbackUrl:location.href
  });
authProvider.on('loginFailure', function($location, error) {
    console.log('ERROR',error);
  });
....

$scope.login = function() {
    auth.signin({
      username:"...",
      password:"...",
      connection:"Username-Password-Authentication",
callbackUrl:location.href
    });
  }
```

The login errors (IE: `Uncaught invalid_user_password: Wrong email or password.`) are not being catched by the `loginFailure` event.

**Comment by Phobos98** [comment] 2016-02-02 14:28
Same problem here :(

**Comment by christiannwamba** [comment] 2016-05-31 13:35
Hi!

Is this an IE specific issue? Does the event work in other browsers for you?

**Comment by christiannwamba** [comment] 2016-06-03 06:56
Hi! I am unable to reproduce this issue and will be closing. Feel free to re-open if necessary

**Closed by christiannwamba** 2016-06-03 06:56 UTC
Labels: Unable to reproduce, waiting for feedback

**Comment by cyxou** [comment] 2016-06-22 08:13
+1 

I'm implementing custom login form and auth0 in redirect mode. The loginFailure event does not fire on wrong email/password error.

**Comment by cyxou** [comment] 2016-06-22 08:49
I think the problem is in [this chunk of code](https://github.com/auth0/auth0-angular/blob/v4.2.3/src/services/auth0.service.js#L482) from the v4.2.3:
```javascript
var errorFn = !errorCallback ? null : function(err) {
  callHandler('loginFailure', { error: err });
  if (errorCallback) {
    errorCallback(err);
  }
};

var signinCall = authUtils.callbackify(signinMethod, successFn, errorFn , innerAuth0libraryConfiguration[libName || config.lib].library());
```

In redirect mode we don't supply success and error callbacks thus the `errorFn` is `null` and the `loginFailure` event never fires. If we supply the noop `function() {}` for success and error callbacks, than the `loginFailure` event will fire, but Auth0 will operate in popup mode which is not desired in my case.

**Comment by cyxou** [comment] 2016-06-22 09:50
I've created a [pull request](https://github.com/auth0/auth0-angular/pull/279) hoping to fix this issue.
