### ISSUE TITLE
App is not returning to initially requested page after login.

### ISSUE THREAD

**Issue by ThomasPrikrylBE** [auth0/auth0-angular#193] opened 2021-08-18 11:12 UTC
Hello,

I upgraded my app to Angular 12 and subsequently this lib to 1.6.0 but ran into the problem that (after a login with redirect) being returned to the callback URL, the app remains at the /callback?code=xxx&state=yyy route and doesn't switch back to the initially requested url. The callback route is an own route in my app, with an empty component that also has an empty template and it is not guarded by the AuthGuard.

My "fix" for this was injecting the AuthService into the /callback component (or my AppComponent directly for that matter). Because then after being returned to the /callback url, the state seems to be getting picked up by the AuthService and hence I get navigated to the initially requested url.

I mean it might be obvious that it won't work if I'm not loading the AuthService somewhere, and not even considered a bug, however I don't actually use the AuthService for anything at that point in time. It is only used for getting the user's name, but that happens later in the process, in another component altogether, when the user has arrived at the initially requested page. And since there is no "init" or other method that could be called, it remains just an unused injected dependency. It is not even used for the login, because the login happens implicitly by accessing a route that is guarded by the AuthGuard (and then being redirected in the aforementioned way).

The problem is that my IDE is (sort of rightfully) marking it as such as well:

`  constructor(private authService: AuthService) {}`

And this could mean that it might be removed automatically by something like a code formatter that removes unused fields/imports/etc. Or by someone who doesn't know why it was injected there. I could of course assign it to something or add a comment to artificially keep it there but that too seems a bit odd.

I'd appreciate any input as to how this should be solved in the correct manner.
Thanks

**Comment by frederikprijck** [comment] 2021-08-18 11:21
Thanks for reaching out, I don't believe this is related to updating both Angular to 12 or our SDK to 1.6.0. 
Our SDK has always worked like this, where it expects you to inject the AuthService in AppComponent (or anything that ensures it is available when getting to /callback).

I understand the fact that it is not ideal to have an unused service being injected, and I am open for PRs to solve this in a non-breaking way.

However, I do not believe this is a bug, as the SDK works as intended.

**Comment by frederikprijck** [comment] 2021-09-23 13:20
Having looked into this, we believe there isn't much we can do here that wouldn't break all existing users.

We will track this internally for any future major version work, but closing the issue here for now as it works as intended.

**Closed as completed by frederikprijck** 2021-09-23 13:20 UTC
Labels: enhancement

**Comment by danmana** [comment] 2022-01-13 11:58
Can we add this to the documentation here https://auth0.com/blog/complete-guide-to-angular-user-authentication/ ?

I wasted a lot of time trying to figure out why switching the callback URL from the landing page `/` to `/callback` stopped working.

It turns out that on the landing page I needed AuthService (to show a login button or a link to the user's homepage if he was already logged in), but on the callback page I had just a spinner, so I did not import the service ....

This outdated Angular 2 documentation mentioned adding a `handleAuthentication` method to the app component. https://auth0.com/docs/get-started/architecture-scenarios/spa-api/spa-implementation-angular2

The new docs should mention that AuthService should be injected in the component handling the callback URL (or the AppComponent)
